custom:
  app:
    token:
      timeout: 86400
  nosql:
    redis:
      host: 127.0.0.1
      port: 6379
    rabbitmq:
      addresses: localhost:5672
      port: 5672
      username: mnet
      password: mnet
  oauth:
    ip: localhost:9710
    clientId: test
    clientSecret: 123456
  #文件上传配置，保存的路径
  upload:
    #文件保存的路径(服务器主机删的绝对路径，如若没有请新建)
    absolute-path: /home/mnet/montnets/images     
    

nacosserver:
  ip: localhost
  port: 8848

sentinelserver:
  ip: localhost
  port: 8080

logging:
  level:
    com.suoju.montnets.common.dao:  DEBUG

token:
  ip: localhost
  expire:
    seconds: 300

